/**
 * Writes .env.test from the running local Supabase stack so the RLS suite never relies on
 * hand-copied keys. SEED_LOGINS is taken from .env.local when present (that is where the real
 * login list lives, never committed), else from the placeholder block in .env.example.
 *
 * Run: pnpm env:local
 */
import { execSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';

function parseEnvFile(path: string): Record<string, string> {
  if (!existsSync(path)) return {};
  const out: Record<string, string> = {};
  for (const line of readFileSync(path, 'utf8').split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (!m) continue;
    let value = m[2];
    if (
      (value.startsWith("'") && value.endsWith("'")) ||
      (value.startsWith('"') && value.endsWith('"'))
    ) {
      value = value.slice(1, -1);
    }
    out[m[1]] = value;
  }
  return out;
}

const status: Record<string, string> = {};
const raw = execSync('pnpm exec supabase status -o env', { encoding: 'utf8' });
for (const line of raw.split(/\r?\n/)) {
  const m = line.match(/^([A-Z0-9_]+)="?([^"]*)"?$/);
  if (m) status[m[1]] = m[2];
}

const required = ['API_URL', 'ANON_KEY', 'SERVICE_ROLE_KEY', 'DB_URL'] as const;
for (const k of required) {
  if (!status[k])
    throw new Error(`supabase status did not return ${k}. Is the stack running? (pnpm db:start)`);
}

const local = parseEnvFile('.env.local');
const example = parseEnvFile('.env.example');
const seedLogins = local.SEED_LOGINS ?? example.SEED_LOGINS;
if (!seedLogins) throw new Error('SEED_LOGINS not found in .env.local or .env.example');
const logins = JSON.parse(seedLogins) as unknown[];
if (!Array.isArray(logins) || logins.length !== 6) {
  throw new Error(
    `SEED_LOGINS must be a JSON array of 6 logins, got ${Array.isArray(logins) ? logins.length : typeof logins}`,
  );
}

const existing = parseEnvFile('.env.test');
const lines = [
  `NEXT_PUBLIC_SUPABASE_URL=${status.API_URL}`,
  `NEXT_PUBLIC_SUPABASE_ANON_KEY=${status.ANON_KEY}`,
  `SUPABASE_SERVICE_ROLE_KEY=${status.SERVICE_ROLE_KEY}`,
  `DATABASE_URL=${status.DB_URL}`,
  `PROVIDER_BASE_URL=https://dispatcher-production-72fc.up.railway.app`,
  `PROVIDER_API_KEY=test-key-not-real`,
  `SEED_LOGINS='${seedLogins}'`,
];
// Keep passwords already generated by seed:users so re-running env:local does not orphan them.
if (existing.SEED_PASSWORDS_JSON)
  lines.push(`SEED_PASSWORDS_JSON='${existing.SEED_PASSWORDS_JSON}'`);
writeFileSync('.env.test', lines.join('\n') + '\n');
console.log(`.env.test written for ${status.API_URL} with ${logins.length} seed logins`);
